import { BoardStatus, ICardData, Status } from '@/interfaces/card.interfaces'

export const data: ICardData[] = [
  {
    id: '1s31s',
    boardStatus: BoardStatus.new,
    primaryTitle: 'UI/UX дизайнер',
    secondaryTitle: 'Отдел разработки мобильного приложения',
    statusText: Status.primary,
    followersCount: 3,
    messagesCount: 255,
    jobTitle: 'Рекруитер',
    name: 'Алексей Щербаков',
    image: '/users/new-user-1.svg'
  },
  {
    id: '3d42r',
    boardStatus: BoardStatus.new,
    primaryTitle: 'Маркетолог',
    secondaryTitle: 'Отдел маркетинга',
    statusText: Status.primary,
    followersCount: 2,
    messagesCount: 182,
    jobTitle: 'Рекруитер',
    name: 'Floyd Miles',
    image: '/users/new-user-2.svg'
  },
  {
    id: '4d2rs',
    boardStatus: BoardStatus.new,
    primaryTitle: 'Менеджер по продажам',
    secondaryTitle: 'Отдел продаж',
    statusText: Status.primary,
    followersCount: 3,
    messagesCount: 255,
    jobTitle: 'Рекруитер',
    name: 'Theresa Webb',
    image: '/users/new-user-3.svg'
  },
  {
    id: '2sy62',
    boardStatus: BoardStatus.new,
    primaryTitle: 'UI/UX дизайнер',
    secondaryTitle: 'Отдел разработки мобильного приложения',
    statusText: Status.primary,
    followersCount: 3,
    messagesCount: 182,
    jobTitle: 'Рекруитер',
    name: 'Vanessa Johnson',
    image: '/users/new-user-4.svg'
  },
  {
    id: 'nmc92',
    boardStatus: BoardStatus.current,
    primaryTitle: 'PHP Developer',
    secondaryTitle: 'Housekeepers',
    statusText: Status.primary,
    followersCount: 3,
    messagesCount: 182,
    jobTitle: 'Рекруитер',
    name: 'Kristin Watson',
    image: '/users/current-user-1.svg'
  },
  {
    id: '9n24d',
    boardStatus: BoardStatus.current,
    primaryTitle: 'Freshers',
    secondaryTitle: 'Finance',
    statusText: Status.secondary,
    followersCount: 3,
    messagesCount: 182,
    jobTitle: 'Рекруитер',
    name: 'Jacob Jones',
    image: '/users/current-user-2.svg'
  },
  {
    id: '2sr5c',
    boardStatus: BoardStatus.current,
    primaryTitle: 'UI UX Designer',
    secondaryTitle: 'Management',
    statusText: Status.primary,
    followersCount: 3,
    messagesCount: 182,
    jobTitle: 'Рекруитер',
    name: 'Wade Warren',
    image: '/users/current-user-3.svg'
  },
  {
    id: 'sfrt5',
    boardStatus: BoardStatus.current,
    primaryTitle: 'Joomla Developer',
    secondaryTitle: 'Accounting',
    statusText: Status.secondary,
    followersCount: 3,
    messagesCount: 182,
    jobTitle: 'Рекруитер',
    name: 'Cameron Williamson',
    image: '/users/current-user-4.svg'
  },
  {
    id: '3wsfe',
    boardStatus: BoardStatus.current,
    primaryTitle: 'Python Developer',
    secondaryTitle: 'Laundry',
    statusText: Status.primary,
    followersCount: 3,
    messagesCount: 182,
    jobTitle: 'Рекруитер',
    name: 'Devon Lane',
    image: '/users/current-user-5.svg'
  },
  {
    id: '2srt1',
    boardStatus: BoardStatus.current,
    primaryTitle: 'Freshers',
    secondaryTitle: 'Finance',
    statusText: Status.secondary,
    followersCount: 3,
    messagesCount: 182,
    jobTitle: 'Рекруитер',
    name: 'Jacob Jones',
    image: '/users/current-user-1.svg'
  },
  {
    id: 'sdwa2',
    boardStatus: BoardStatus.archived,
    primaryTitle: 'UX Architect',
    secondaryTitle: 'Housekeeping management',
    statusText: Status.primary,
    followersCount: 3,
    messagesCount: 182,
    jobTitle: 'Рекруитер',
    name: 'Guy Hawkins',
    image: '/users/archive-user-1.svg'
  },
  {
    id: '2ae45',
    boardStatus: BoardStatus.archived,
    primaryTitle: 'Human Resource',
    secondaryTitle: 'Operations',
    statusText: Status.important,
    followersCount: 2,
    messagesCount: 182,
    jobTitle: 'Рекруитер',
    name: 'Annette Black',
    image: '/users/archive-user-1.svg'
  },
  {
    id: '01ain',
    boardStatus: BoardStatus.archived,
    primaryTitle: 'Python Developer',
    secondaryTitle: 'Restaurant Management',
    statusText: Status.important,
    followersCount: 3,
    messagesCount: 255,
    jobTitle: 'Рекруитер',
    name: 'Esther Howard',
    image: '/users/archive-user-3.svg'
  },
  {
    id: 'a1wex',
    boardStatus: BoardStatus.deleted,
    primaryTitle: 'UI/UX дизайнер',
    secondaryTitle: 'Отдел разработки мобильного приложения',
    statusText: Status.primary,
    followersCount: 3,
    messagesCount: 255,
    jobTitle: 'Рекруитер',
    name: 'Алексей Щербаков',
    image: '/users/new-user-1.svg'
  },
  {
    id: '2ase4',
    boardStatus: BoardStatus.deleted,
    primaryTitle: 'UI/UX дизайнер',
    secondaryTitle: 'Отдел разработки мобильного приложения',
    statusText: Status.primary,
    followersCount: 3,
    messagesCount: 255,
    jobTitle: 'Рекруитер',
    name: 'Алексей Щербаков',
    image: '/users/new-user-1.svg'
  },
  {
    id: '2ase3',
    boardStatus: BoardStatus.deleted,
    primaryTitle: 'UI/UX дизайнер',
    secondaryTitle: 'Отдел разработки мобильного приложения',
    statusText: Status.primary,
    followersCount: 3,
    messagesCount: 255,
    jobTitle: 'Рекруитер',
    name: 'Алексей Щербаков',
    image: '/users/new-user-1.svg'
  },
  {
    id: '2awet',
    boardStatus: BoardStatus.deleted,
    primaryTitle: 'UI/UX дизайнер',
    secondaryTitle: 'Отдел разработки мобильного приложения',
    statusText: Status.primary,
    followersCount: 3,
    messagesCount: 255,
    jobTitle: 'Рекруитер',
    name: 'Алексей Щербаков',
    image: '/users/new-user-1.svg'
  }
]
